//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSupport.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.DEPARTMENT_OPTION = new HashSet<DEPARTMENT_OPTION>();
            this.STUDENT_LEVEL = new HashSet<STUDENT_LEVEL>();
        }
    
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public string Department_Code { get; set; }
        public Nullable<int> Faculty_Id { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        public virtual ICollection<DEPARTMENT_OPTION> DEPARTMENT_OPTION { get; set; }
        public virtual ICollection<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
    }
}
