//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSupport.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY
    {
        public FACULTY()
        {
            this.DEPARTMENT = new HashSet<DEPARTMENT>();
        }
    
        public int Faculty_Id { get; set; }
        public string Faculty_Name { get; set; }
        public string Faculty_Description { get; set; }
    
        public virtual ICollection<DEPARTMENT> DEPARTMENT { get; set; }
    }
}
