//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSupport.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.USER = new HashSet<USER>();
        }
    
        public long Person_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public Nullable<int> Sex_Id { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
    
        public virtual SEX SEX { get; set; }
        public virtual ICollection<USER> USER { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
