//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSupport.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public int Ticket_Id { get; set; }
        public Nullable<int> Ticket_Serial_Number { get; set; }
        public string Ticket_Number { get; set; }
        public long Person_Id { get; set; }
        public string Complaint { get; set; }
        public string Reply { get; set; }
        public System.DateTime Date_Submitted { get; set; }
        public Nullable<System.DateTime> Date_Replied { get; set; }
        public bool Activated { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
